# These settings are synced to GitHub by https://probot.github.io/apps/settings/
_extends: plumbing

repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: gh-tf-provider-playground

  # A short description of the repository that will show up on GitHub
  description: Playground for Terraform Provider Development

  # A URL with more information about the repository
  homepage:

  # A comma-separated list of topics to set on the repository
  topics: terraform, terraform-provider, playground
