name: Release Flow

on:
  release:
    types: [published]
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      #- name: Import GPG key
      #  id: import_gpg
      #  uses: crazy-max/ghaction-import-gpg@v2
      #  env:
      #    GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      #    PASSPHRASE: ${{ secrets.PASSPHRASE }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #  GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}

  publish_docs:
    name: Publish the HTML Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2.3.2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
