name: Release Process

on:
  workflow_dispatch:
    #inputs:
    #  logLevel:
    #    description: 'Log level'
    #    required: true
    #    default: 'warning'
    #  tags:
    #    description: 'Test scenario tags'
jobs:
  release-process:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Starting"
          echo "Tags: ${{ toJson(github) }}"
      - uses: octokit/request-action@v2.0.19
        id: get_latest_release
        with:
          route: GET /repos/:repository/releases
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo latest release: fff"
      - run: |
          echo "::set-env name=DRAFTE_RELESE_VERSION::${{ fromJson(steps.get_latest_release.outputs.data)[0].name }}"
          echo "::set-env name=DRAFTE_RELESE_ID::${{ fromJson(steps.get_latest_release.outputs.data)[0].id }}"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth:  0
      - run: |
          git checkout -b release/${{ env.DRAFTE_RELESE_VERSION }}

      - name: Install dependencies
        run: |
          echo "::add-path::/home/runner/.local/bin"
          python -m pip install --upgrade pip
          pip install MarkdownPP mkdocs
      - name: Install dependencies
        run: |
          cd ./documentation && go run mage.go -v GenerateDocumation

      # https://github.com/EndBug/add-and-commit
      - uses: EndBug/add-and-commit@v4 # You can change this to use a specific version
        with:
          add: 'docs'
          force: true
          #tag: "${{ env.DRAFTE_RELESE_VERSION }}"
          ref: "release/${{ env.DRAFTE_RELESE_VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: octokit/request-action@v2.0.19
        id: publish_latest_release
        with:
          route: PATCH /repos/:repository/releases/:release_id
          repository: ${{ github.repository }}
          release_id: ${{ env.DRAFTE_RELESE_ID }}
          tag_name: ${{ env.DRAFTE_RELESE_VERSION }}
          target_commitish: "release/${{ env.DRAFTE_RELESE_VERSION }}"
          draft: false
          mediaType: | # The | is significant!
            previews:
              - antiope
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
