name: Release Process

on:
  workflow_dispatch:
    #inputs:
    #  logLevel:
    #    description: 'Log level'
    #    required: true
    #    default: 'warning'
    #  tags:
    #    description: 'Test scenario tags'
jobs:
  release-process:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Starting"
          echo "Tags: ${{ toJson(github) }}"
      - uses: octokit/request-action@v2.0.12
        id: get_latest_release
        with:
          route: GET /repos/:repository/releases
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo latest release: fff"
      - run: |
          echo ${{ fromJson(steps.get_latest_release.outputs.data)[0].name }}
      - run: |
          env
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth:  0
      - run: |
          git checkout -b release/${{ fromJson(steps.get_latest_release.outputs.data)[0].name }}

      - name: Install dependencies
        run: |
          echo "::add-path::${{ HOME }}/.local/bin"
          python -m pip install --upgrade pip
          pip install MarkdownPP mkdocs
      - name: Install dependencies
        run: |
          cd ./documentation && go run mage.go -v GenerateDocumation

      - uses: EndBug/add-and-commit@v4 # You can change this to use a specific version
        with:
          add: 'docs'
          force: true
          tag: "${{ fromJson(steps.get_latest_release.outputs.data)[0].name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
