name: Release Process

on:
  workflow_dispatch:
    #inputs:
    #  logLevel:
    #    description: 'Log level'
    #    required: true
    #    default: 'warning'
    #  tags:
    #    description: 'Test scenario tags'
jobs:
  release-process:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Starting"
          echo "Tags: ${{ toJson(github) }}"
      - uses: octokit/request-action@v2.0.12
        id: get_latest_release
        with:
          route: GET /repos/:repository/releases
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo latest release: fff"
      - run: |
          echo ${{ steps.get_latest_release.outputs.data[0]['name'] }}
      - run: |
          env
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth:  0
